version: '3.8'

services:
  incidents-microservice:
    build: ..
    ports:
      - "5007:5007"
    environment:
      - FLASK_ENV=development
      - DB_HOST=incidents-db
      - DB_PORT=5432
      - DB_NAME=incidents_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - incidents-db
    networks:
      - abc-call-network

  incidents-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=incidents_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_incidents:/var/lib/postgresql/data
    networks:
      - abc-call-network

volumes:
  postgres_data_incidents:

networks:
  abc-call-network:
    external: true