version: '3.8'

services:
  incidents-microservice:
    build: ..
    ports:
      - "5007:5007"
    environment:
      - FLASK_ENV=development
      - DB_HOST=incidents-db
      - DB_PORT=5433
      - DB_NAME=incidents_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - incidents-db

  incidents-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=incidents_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  abc-call-network:
    external: true